Repository u-sho/quantum-game-arena, pull requests merged in 2022-04, with the labels that each got.

#75 add snyk and remove `<dialog>` polyfill
  .github/workflows/codeql-analysis.yml
  .github/workflows/lintcheck-and-test.yaml
  .github/workflows/snyk-analysis.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/lib/games/AppBanner.svelte
  src/lib/games/quantum-tictactoe/OfflineApp.svelte
  src/lib/games/quantum-tictactoe/QuantumTTT.ts
Labels: environment

#78 upgrade TypeScript and its compiler options
  package-lock.json
  package.json
  src/lib/types/test/generics.test.ts
  tsconfig.json
Labels: environment

#79 upgrade SvelteKit and others
  .eslintignore
  .eslintrc.cjs
  jest.config.cjs
  package-lock.json
  package.json
  src/lib/games/AppBanner.svelte
  src/lib/games/quantum-tictactoe/QuantumTTT.ts
  src/lib/types/generics.ts
  src/routes/__error.svelte
  src/routes/games/quantum-tictactoe/index.svelte
  src/routes/games/quantum-tictactoe/play/[roomId].svelte
  src/routes/games/quantum-tictactoe/tutorial/index.svelte
  src/routes/index.svelte
  src/service-worker/index.ts
  svelte.config.js
  tsconfig.json
Labels: site; frontend, environment

#80 remove first tab indent in `<script>` and `<style>`
  .prettierrc
  src/lib/TheFooter/index.svelte
  src/lib/TheHeader/index.svelte
  src/lib/assets/logo-title_row-colored.svg.svelte
  src/lib/assets/logo-title_row-white.svg.svelte
  src/lib/assets/logo_white.svg.svelte
  src/lib/assets/twitter-logo_white.svg.svelte
  src/lib/games/AppBanner.svelte
  src/lib/games/quantum-tictactoe/GameBoard.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/MarkClassical.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/MarkQuantums.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/index.svelte
  src/lib/games/quantum-tictactoe/GameInfo.svelte
  src/lib/games/quantum-tictactoe/OfflineApp.svelte
  src/routes/__error.svelte
  src/routes/__layout.svelte
  src/routes/games/quantum-tictactoe/index.svelte
  src/routes/games/quantum-tictactoe/play/[roomId].svelte
  src/routes/games/quantum-tictactoe/play/human.svelte
  src/routes/games/quantum-tictactoe/tutorial/index.svelte
  src/routes/index.svelte
Labels: site; frontend

#53 ヘッダー画像の改善
  package-lock.json
  package.json
  src/global.d.ts
  src/lib/TheFooter/index.svelte
  src/lib/types/svelte-scrollto.d.ts
  src/routes/games/quantum-tictactoe/index.svelte
  src/routes/games/quantum-tictactoe/tutorial/index.svelte
  src/routes/index.svelte
Labels: site; frontend

#81 v0.5.0 Hero Image Improvement
  .eslintignore
  .eslintrc.cjs
  .github/workflows/codeql-analysis.yml
  .github/workflows/lintcheck-and-test.yaml
  .github/workflows/snyk-analysis.yml
  .gitignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  jest.config.cjs
  package-lock.json
  package.json
  src/global.d.ts
  src/lib/TheFooter/index.svelte
  src/lib/TheHeader/index.svelte
  src/lib/assets/logo-title_row-colored.svg.svelte
  src/lib/assets/logo-title_row-white.svg.svelte
  src/lib/assets/logo_white.svg.svelte
  src/lib/assets/twitter-logo_white.svg.svelte
  src/lib/games/AppBanner.svelte
  src/lib/games/quantum-tictactoe/GameBoard.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/MarkClassical.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/MarkQuantums.svelte
  src/lib/games/quantum-tictactoe/GameBoardSquare/index.svelte
  src/lib/games/quantum-tictactoe/GameInfo.svelte
  src/lib/games/quantum-tictactoe/OfflineApp.svelte
  src/lib/games/quantum-tictactoe/QuantumTTT.ts
  src/lib/types/generics.ts
  src/lib/types/svelte-scrollto.d.ts
  src/lib/types/test/generics.test.ts
  src/routes/__error.svelte
  src/routes/__layout.svelte
  src/routes/games/quantum-tictactoe/index.svelte
  src/routes/games/quantum-tictactoe/play/[roomId].svelte
  src/routes/games/quantum-tictactoe/play/human.svelte
  src/routes/games/quantum-tictactoe/tutorial/index.svelte
  src/routes/index.svelte
  src/service-worker/index.ts
  svelte.config.js
  tsconfig.json
Labels: site; frontend
